[supervisord]
nodaemon=true

[program:queue-worker]
command=php /var/www/html/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
user=www-data
numprocs=1
autostart=true
autorestart=true
startsecs=1
startretries=3
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/queue-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

